### ISSUE TITLE
How to uninstall whatever this thing installs?

### ISSUE THREAD

**Issue by 103sbavert** [Kafels/AlsaMixerFreeze#1]
I installed but now I want to uninstall because it doesn't work for me

**Comment by Kafels** [comment]
Hi @sbeve72, I'll create a script to uninstall. But, to do it manually, you must do these three steps:

### First
```bash
nano ~/.profile

# Delete these lines and save it
# AlsaMixer Freeze
alsamixer-freeze
```

### Second

```bash
# Delete python script
rm $HOME/.local/bin/alsamixer-freeze
```

### Third

```bash
# Reboot
sudo reboot -f
```

Also, could you share your configuration and what happened? I would like to improve it.

**Comment by 103sbavert** [comment]
Where can I find my configuration? BTW this thing doesn't work for me so I had to uninstall it. I can reinstall and share the configuration with you if that's what you're asking for.

**Comment by Kafels** [comment]
Your operation system version and python version it's enough to me

**Comment by Kafels** [comment]
Your OS version and python version is enough for me

**Comment by 103sbavert** [comment]
I am sorry I forgot to respond to this

My OS version was KDE Neon 5.22
and python 3.9
