### ISSUE TITLE
Create a script to uninstall

### ISSUE THREAD

**Issue by Kafels** [Kafels/AlsaMixerFreeze#2]
At the moment, to remove everything it's necessary to delete `alsamixer-freeze` command from `~/.profile`, execute `rm $HOME/.local/bin/alsamixer-freeze` and reboot the system.

**Comment by Blastoise** [comment]
I would like to contribute on this.

**Comment by Kafels** [comment]
What I need to do to help you? I have never managed a open repository

**Comment by Blastoise** [comment]
Nothing just add this label on the pull request I'll do to the repository.
**hacktoberfest-accepted**
